### ISSUE TITLE
As a cashier, I want to add and remove inventory item from the sale.

### ISSUE THREAD

**Issue by RiggiG** [cse442-fall-2019-offering/442projects-team-7#13]

**Comment by Se4musty** [comment]
Add product to sale by it's correct SKU acceptance test:

1.) Perform the "Correct Login Acceptance Test" for user story #4.
2.) Once arrived at the main POS page, navigate to the box labeled "Enter a SKU, scan barcode, or search for item...", click on the inside of this box.
3.) Type: "556278", and click the button to the right of this box labeled "Search Item".
4.) A corresponding product will be placed at the start of the table below, which has the same SKU #, a corresponding item description, and its unit price.

**Comment by Se4musty** [comment]
Delete a product from the sale acceptance test:

1.) Perform the "Add product to sale by it's correct SKU acceptance test" above.
2.) Navigate the table which has the newly appended product from step 1.
3.) Select the newly created item by clicking on it.
4.) The item should now be highlighted.
5.) Click the "Delete Item" button found above the table.
6.) The item should now be removed from the table. Indicating that an item has been removed from the sale.
