### ISSUE TITLE
As a cashier, I want to search inventory items based on stored information.

### ISSUE THREAD

**Issue by RiggiG** [cse442-fall-2019-offering/442projects-team-7#14]

**Comment by Se4musty** [comment]
Get a table listing of all DB items acceptance test:

1.) Perform the "Correct Login Acceptance Test" for user story #4.
2.) Once you arrived at the main POS page, navigate to the button labeled "Edit Items" found towards the top of the page.
3.) Click the "Edit Items" button.
4.) A popup window should now appear with a title at the very top of the page labeled "Item Manipulator". There should also be a title for the table below this labeled "Item Manipulation".
5.) To get a listing of all DB products, click the button at the button labeled "Refresh Table".
6.) The table above this listing should should now contain a listing of products. The first product entry will have an SKU of "556278" and the last product entry will have and SKU of "556293".

**Comment by Se4musty** [comment]
Select and remove an item from the table acceptance test:

1.) Perform the "Get a table listing of all DB items acceptance test" above.
2.) Select the item labeled "Example_7" from the updated table listing of database items by clicking that row.
3.) The product should now be highlighted in white.
4.) Navigate to the button labeled "Delete", and click on it.
5.) The product should now be removed from the table. Indicating that the selected product has been removed from the manipulation table.
