### ISSUE TITLE
As a cashier, I want to edit the quantity of an item in the sale.

### ISSUE THREAD

**Issue by RiggiG** [cse442-fall-2019-offering/442projects-team-7#15]
As a cashier, the quantity of an item should be easily manipulated in the main Point of Sale user interface. The product total should also be changed to reflect this.

**Comment by Se4musty** [comment]
**Negative Quantity Acceptance Test**:
 1. Login to the point of sale by entering credentials `edmund:qwerty` and clicking the Login button.
 2. Click the text-box towards the upper-left portion of the page with the following text: 'Enter a SKU, scan barcode, or search for item...'.
3. Type the number '1', and click the 'Search Item' button to the right of the text-box.
4. An item with an SKU column value of '1' should now appear in the table below the text-box. Select this product by clicking on 'Example_1'.
5. The row should now be highlighted in white, the Unit Price will now be enabled for editing. Hover over the 'Qty' column value of '1', two arrows should now be displayed to the right of the quantity value. 
6. Click the arrow pointing vertically downwards twice.

**Success condition:** The 'Qty' column value should be 0 as negative quantities are not valid. The 'Total' column value should be 0.00 to reflect this.
**Failure condition:** The Qty is '-1'.

**Comment by Se4musty** [comment]
**Duplicate SKU Quantity Acceptance Test**:
 1. Login to the point of sale by entering credentials `edmund:qwerty` and clicking the Login button.
 2. Click the text-box towards the upper-left portion of the page with the following text: 'Enter a SKU, scan barcode, or search for item...'.
3. Type the number '1', and click the 'Search Item' button to the right of the text-box.
4. An item with an SKU column value of '1' should now appear in the table below the text-box. 
5. Perform steps 2-4 a once more.

**Success condition:** The 'Qty' column value should be '2'. The 'Total' column value should be to 89.98 reflect this.
**Failure condition:** Two products should now exist within the table below, each with a quantity of '1' and the same Description column value of 'Example_1'.
