### ISSUE TITLE
Switch from Login Window to Cashier Default Window when a correct user/pass is entered

### ISSUE THREAD

**Issue by joxpUB** [cse442-fall-2019-offering/442projects-team-7#32]
Accept a single hardcoded user/pass for Sprint 1

**Comment by WhalePower** [comment]
Basic login and registration functionality tested using console.
Commit - [4e6b0d9](https://github.com/cse442-fall-2019-offering/442projects-team-7/commit/4e6b0d98ff238dff464bb7d5b4f67a65058ba131)

**Comment by WhalePower** [comment]
Removed registration option.
Commit - [2bebfcc](https://github.com/cse442-fall-2019-offering/442projects-team-7/commit/2bebfcca128a02fd746471f8f72673a300a74dd9)
