### ISSUE TITLE
As a cashier, I want to login with my credentials so that I can see the main POS display.

### ISSUE THREAD

**Issue by RiggiG** [cse442-fall-2019-offering/442projects-team-7#4]

**Comment by Se4musty** [comment]
Login Acceptance Test:

1.) From the login display, navigate to the box labeled "Username:". Click the box and type "edmund".
2.) Navigate to the box labeled "Password:", click the box and type "qwerty".
3.) Navigate the the "Submit" button, click the button.
4.) The application should now display a new page with a box that has the text "Enter a SKU, scan barcode, or search for item...", this means that you have successfully changed to the main POS display.

**Comment by joxpUB** [comment]
Incorrect Login Acceptance Test:

1.) From the login display, navigate to the box labeled "Username:". Click the box and type anything but "edmund".
2.) Navigate to the box labeled "Password:", click the box and type anything but "qwerty".
3.) Navigate the the "Submit" button, click the button.
4.) The application should now display a new page with a box that has the text "Enter a SKU, scan barcode, or search for item...", this means that you have successfully changed to the main POS display.
