### ISSUE TITLE
Customer Lookup Window

### ISSUE THREAD

**Issue by Se4musty** [cse442-fall-2019-offering/442projects-team-7#48]
Create a pop-up window used to select (for current order), add, modify, and delete customer datastore entries.

**Comment by Se4musty** [comment]
Created a Figma mockup for a possible customer lookup window.

![Capture.PNG](https://images.zenhubusercontent.com/5d73172d6e37a9304006c243/9e789d59-338f-44e9-8aa9-f613df8dac3e)

**Comment by WhalePower** [comment]
**Customer Lookup Window Popup Test**

1.) From the login display, navigate to the box labeled 'Username:'. Click on the box and type 'edmund'.

2.) Navigate to the box labeled 'Password:', click the box and type 'qwerty'.

3.) Click on the button labeled 'Submit'.

4.) The window should transition to a new main window with a button on the upper-left portion of the screen labeled 'Customer Lookup'. Click on the button labeled 'Customer Lookup'.

**Success Condition:** The 'Customer Lookup' popup window opens up
