### ISSUE TITLE
As a cashier, I want to select a customer when making a sale.

### ISSUE THREAD

**Issue by RiggiG** [cse442-fall-2019-offering/442projects-team-7#9]

**Comment by Se4musty** [comment]
Select an Existing Customer Acceptance Test:

1.) From the login display, navigate to the box labeled 'Username:'. Click the box and type 'edmund'.
2.) Navigate to the box labeled 'Password:', click the box and type 'qwerty'.
3.) Navigate the 'Submit' button, click the button.
4.) The application should now have a new main window, with a button towards the upper-left portion of the screen labeled 'Customer Lookup'. Navigate to the 'Customer Lookup' button and click it.
5.) The application should now have a new popup window labeled 'Customer Lookup'. Navigate to the bottom-left corner of the 'Customer Lookup' window and you should see a button labeled 'Refresh Table'. Click the 'Refresh Table' button.
6.) The 'Customer Lookup' window's table should now be updated with our currently stored customer information. Navigate to the row of the 'Customer Lookup' table which has the column name 'Jonathan Wick', then click that corresponding row. The row should now be highlighted to indicate it has been selected.
7.) Navigate to the bottom-left corner of the 'Customer Lookup' window and you should see a button labeled 'Select', then click the button. Then, navigate to the bottom-left of the 'RPi Point of Sale - Cashier Default Window'.

**Success condition:** The 'Customer Info' section of the  'RPi Point of Sale - Cashier Default Window' should now be populated with the followng information from top to bottom: '268567', 'Jonathan Wick', '(716) 505-612', 'jwick@gmail.com'.

**Failure condition:** Either a different series of information is displayed in the 'Customer Info' section or no information is displayed.

**Comment by Se4musty** [comment]
**Prevent Selection of Undefined Customer Acceptance Test**:

1.) From the login display, navigate to the box labeled 'Username:'. Click the box and type 'edmund'.
2.) Navigate to the box labeled 'Password:', click the box and type 'qwerty'.
3.) Navigate the 'Submit' button, click the button.
4.) The application should now have a new main window, with a button towards the upper-left portion of the screen labeled 'Customer Lookup'. Navigate to the 'Customer Lookup' button and click it.
5.) The application should now have a new popup window labeled 'Customer Lookup'. Navigate to any blank row of the 'Customer Lookup' table, then click that corresponding row. The row should now be highlighted to indicate it has been selected.
7.) Navigate to the bottom-left corner of the 'Customer Lookup' window and you should see a button labeled 'Select', then click the button. Then, navigate to the bottom-left of the 'RPi Point of Sale - Cashier Default Window'.

**Success condition:** The 'Customer Info' section of the  'RPi Point of Sale - Cashier Default Window' should contain the previous series of information for 'Jonathan Wick'.

**Failure condition:** All of the information underneath the 'Customer Info' section of the  'RPi Point of Sale - Cashier Default Window' will be 'undefined'.
